highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: https://emspot.github.io/ImohEdet.github.io/
author: Fábio Madeira

# edit this section with your information
# ImohEdet.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /ImohEdet.github.io/
title: Imoh Edet CV
name: Imoh Edet
email: imohdt06@gmail.com
email_full: mailto:imohdt06@gmail.com
website: ImohEdet.github.io
website_full: https://emspot.github.io/ImohEdet.github.io/
github: trending
twitter: twitter
tel: +358406102883
address:
  street: Taidonkaari 1 D 4
  postcode: 90570
  city: Oulu
  country: Finland

# needed for travis-ci build
exclude: [vendor]
